# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/editTransformation.ui'
#
# Created: Tue Apr 19 20:40:20 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(579, 449)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.nameEdit = QtGui.QLineEdit(Dialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.inputCrsEdit = QtGui.QLineEdit(Dialog)
        self.inputCrsEdit.setObjectName("inputCrsEdit")
        self.gridLayout.addWidget(self.inputCrsEdit, 1, 1, 1, 1)
        self.selectInputCrsBtn = QtGui.QToolButton(Dialog)
        self.selectInputCrsBtn.setObjectName("selectInputCrsBtn")
        self.gridLayout.addWidget(self.selectInputCrsBtn, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.outputCrsEdit = QtGui.QLineEdit(Dialog)
        self.outputCrsEdit.setObjectName("outputCrsEdit")
        self.gridLayout.addWidget(self.outputCrsEdit, 2, 1, 1, 1)
        self.selectOutputCrsBtn = QtGui.QToolButton(Dialog)
        self.selectOutputCrsBtn.setObjectName("selectOutputCrsBtn")
        self.gridLayout.addWidget(self.selectOutputCrsBtn, 2, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridRadio = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridRadio.sizePolicy().hasHeightForWidth())
        self.gridRadio.setSizePolicy(sizePolicy)
        self.gridRadio.setChecked(True)
        self.gridRadio.setObjectName("gridRadio")
        self.gridLayout_2.addWidget(self.gridRadio, 0, 0, 1, 1)
        self.gridCombo = QtGui.QComboBox(self.groupBox)
        self.gridCombo.setEditable(True)
        self.gridCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.gridCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.gridCombo.setObjectName("gridCombo")
        self.gridLayout_2.addWidget(self.gridCombo, 0, 1, 1, 1)
        self.towgs84Radio = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.towgs84Radio.sizePolicy().hasHeightForWidth())
        self.towgs84Radio.setSizePolicy(sizePolicy)
        self.towgs84Radio.setObjectName("towgs84Radio")
        self.gridLayout_2.addWidget(self.towgs84Radio, 1, 0, 1, 1)
        self.towgs84Edit = QtGui.QLineEdit(self.groupBox)
        self.towgs84Edit.setEnabled(False)
        self.towgs84Edit.setObjectName("towgs84Edit")
        self.gridLayout_2.addWidget(self.towgs84Edit, 1, 1, 1, 2)
        self.selectGridBtn = QtGui.QToolButton(self.groupBox)
        self.selectGridBtn.setObjectName("selectGridBtn")
        self.gridLayout_2.addWidget(self.selectGridBtn, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.inputCustomCrsNameEdit = QtGui.QLineEdit(self.groupBox_2)
        self.inputCustomCrsNameEdit.setObjectName("inputCustomCrsNameEdit")
        self.gridLayout_3.addWidget(self.inputCustomCrsNameEdit, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.outputCustomCrsNameEdit = QtGui.QLineEdit(self.groupBox_2)
        self.outputCustomCrsNameEdit.setObjectName("outputCustomCrsNameEdit")
        self.gridLayout_3.addWidget(self.outputCustomCrsNameEdit, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 5, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.extentGroup = QtGui.QGroupBox(Dialog)
        self.extentGroup.setCheckable(True)
        self.extentGroup.setChecked(False)
        self.extentGroup.setObjectName("extentGroup")
        self.gridLayout_5 = QtGui.QGridLayout(self.extentGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.extentSelector = ExtentSelector(self.extentGroup)
        self.extentSelector.setObjectName("extentSelector")
        self.gridLayout_5.addWidget(self.extentSelector, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.extentGroup, 4, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QObject.connect(self.towgs84Radio, QtCore.SIGNAL("toggled(bool)"), self.towgs84Edit.setEnabled)
        QtCore.QObject.connect(self.gridRadio, QtCore.SIGNAL("toggled(bool)"), self.gridCombo.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Setup a transformation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Transformation name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Input CRS", None, QtGui.QApplication.UnicodeUTF8))
        self.selectInputCrsBtn.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Output CRS", None, QtGui.QApplication.UnicodeUTF8))
        self.selectOutputCrsBtn.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Transformation params", None, QtGui.QApplication.UnicodeUTF8))
        self.gridRadio.setText(QtGui.QApplication.translate("Dialog", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.towgs84Radio.setText(QtGui.QApplication.translate("Dialog", "towgs84", None, QtGui.QApplication.UnicodeUTF8))
        self.selectGridBtn.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Generated Custom CRSs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Input custom CRS name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Output custom CRS name", None, QtGui.QApplication.UnicodeUTF8))
        self.extentGroup.setTitle(QtGui.QApplication.translate("Dialog", "Extent", None, QtGui.QApplication.UnicodeUTF8))

from ..extentSelector import ExtentSelector
